import csv
import re
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Path Configuration
# ---------------------------------------------------------------------------
# Resolve the absolute path of the directory containing this script.
SCRIPT_DIR = Path(__file__).resolve().parent

# Go up two levels to get the root of the repository: your_repo/
PROJECT_ROOT = SCRIPT_DIR.parent.parent

# Define the absolute paths to the input YAML and output CSV
YAML_PATH = PROJECT_ROOT / "scripts" / "build_tech_codes" / "tech_code_definitions.yaml"
CSV_OUT_PATH = PROJECT_ROOT / "docs" / "assets" / "measurement_tech_codes.csv"


# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------
def parse_block(block, category_dict, details_dict):
    """
    Decodes a single functional block (e.g., 'GCca', 'DA', '00')
    into a human-readable string based on the YAML dictionaries.
    """
    if block == "00":
        return "None / Standard Configuration (00)"

    # The first two characters are ALWAYS the broad uppercase code
    broad_code = block[:2]
    # Anything after the first two characters is the optional lowercase detail suffix
    detail_code = block[2:]

    # Look up the broad category name
    broad_name = category_dict.get(broad_code, f"Unknown ({broad_code})")

    # If a lowercase suffix exists, look it up in the nested details dictionary
    if detail_code:
        # Safely attempt to get the nested detail name
        detail_name = details_dict.get(broad_code, {}).get(
            detail_code, f"Unknown ({detail_code})"
        )
        return f"{broad_name} ({broad_code}) - {detail_name} ({detail_code})"
    else:
        return f"{broad_name} ({broad_code})"


# ---------------------------------------------------------------------------
# Main Execution
# ---------------------------------------------------------------------------
def main():
    # 1. Load the YAML data
    if not YAML_PATH.exists():
        print(f"Error: Could not find YAML file at {YAML_PATH}")
        return

    with open(YAML_PATH, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    dictionaries = data.get("dictionaries", {})
    acq_dict = dictionaries.get("acquisition", {})
    cond_dict = dictionaries.get("conditioning", {})
    det_dict = dictionaries.get("detection", {})
    details_dict = dictionaries.get("details", {})

    active_codes = data.get("active_codes", {})

    # Prepare CSV headers based on the 3-step physical pathway
    headers = [
        "measurement_technology_code",
        "Acquisition",
        "Conditioning",
        "Detection",
        "Example Instruments",
    ]

    # Ensure the destination directory (docs/assets) exists
    CSV_OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # 2. Open and write the CSV
    with open(CSV_OUT_PATH, "w", newline="", encoding="utf-8") as csvfile:
        # Add a warning header so people don't manually edit the generated CSV
        csvfile.write(
            "# =====================================================================\n"
        )
        csvfile.write("# WARNING: AUTO-GENERATED FILE\n")
        csvfile.write(
            "# Do not edit this file directly. Any changes will be overwritten.\n"
        )
        csvfile.write(
            "# To add or modify codes, edit scripts/tech_code_definitions.yaml\n"
        )
        csvfile.write(
            "# =====================================================================\n"
        )

        writer = csv.writer(csvfile)
        writer.writerow(headers)

        # Regex to mathematically enforce the hierarchical upper/lower rules:
        # Block 1: 2 Uppercase, 0-2 lowercase
        # Block 2: 2 Uppercase, 0-2 lowercase OR exactly '00'
        # Block 3: 2 Uppercase, 0-2 lowercase
        validation_pattern = re.compile(
            r"^([A-Z]{2}[a-z]{0,2})-([A-Z]{2}[a-z]{0,2}|00)-([A-Z]{2}[a-z]{0,2})$"
        )

        count = 0

        # 3. Process each approved code in the active_codes list
        for code, example in active_codes.items():
            # Instantly catch invalid codes and skip them
            if not validation_pattern.match(code):
                print(f"Warning: Code '{code}' fails formatting rules. Skipping.")
                continue

            # Split the code perfectly along the hyphens
            blocks = code.split("-")

            # Parse each chunk independently against the corresponding dictionary
            acq_str = parse_block(blocks[0], acq_dict, details_dict)
            cond_str = parse_block(blocks[1], cond_dict, details_dict)
            det_str = parse_block(blocks[2], det_dict, details_dict)

            # Write the denormalized row
            writer.writerow([code, acq_str, cond_str, det_str, example])
            count += 1

    print(f"Success: Generated {CSV_OUT_PATH.name} with {count} valid active codes.")


if __name__ == "__main__":
    main()
