version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libcairo2
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libgdk-pixbuf2.0-0
    - libffi-dev

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml