site_name: AQDx Standard Format Guidance

nav:
  - Introduction: index.md
  - Data Field Definitions:
      - Field Dictionary: standard-format/field-dictionary.md
      - Data Types & Valid Values: standard-format/data-types.md
  - Data File Formats:
      - Tabular Files (CSV/Excel): standard-format/tabular-format.md
      - JSON & Streaming: standard-format/json-format.md
      - Example Records: standard-format/examples.md
  - Metadata Guidance:
      - Overview: metadata/overview.md
      - Data Steward Details: metadata/steward-info.md
      - Site Details: metadata/site-info.md
      - Instrument Details: metadata/instrument-info.md
      - Data Quality Details: metadata/quality-info.md
  - Appendices:
      - Parameter Codes and Method Codes: appendices/parameter-codes.md
      - Unit Codes: appendices/unit-codes.md
      - Qualifier Codes: appendices/qualifier-codes.md
      - Glossary: appendices/glossary.md
      - Version Changelog: appendices/changelog.md

theme:
  name: material

extra_css:
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/fixedcolumns/4.3.0/css/fixedColumns.dataTables.min.css  # <--- NEW CSS

extra_javascript:
  - https://code.jquery.com/jquery-3.7.0.min.js
  - https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js
  - https://cdn.datatables.net/fixedcolumns/4.3.0/js/dataTables.fixedColumns.min.js    # <--- NEW JS
  - https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js

plugins:
  - search
  - with-pdf:
      cover_subtitle: "Version 3.0 - January 2025"

site_author: Colorado Department of Public Health and Environment (CDPHE)
copyright: " "
